services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # Cache do cargo para não ter que baixar/compilar crates toda vez
      - cargo-registry:/usr/local/cargo/registry
      - cargo-target:/app/target
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/postgres
    depends_on:
      - db
    # Usando o cargo-watch para recarregar a aplicação em tempo de desenvolvimento
    command: sleep infinity

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres:
  cargo-registry:
  cargo-target: